#!/bin/bash

SWITCH="\033["
NORMAL="${SWITCH}0m"
RED="${SWITCH}1;31m"
GREEN="${SWITCH}1;32m"

echo running pre-push commands

echo switch dir
ch # todo re-think how to do this...

./run_tests.shl
if [ $? -eq 0 ]; then
    printf "${GREEN}A L L   T E S T S   P A S S E D${NORMAL}\n"
else
    printf "${RED}T E S T S   F A I L E D   ( o r   n o t   r u n ) ,   N O T   P U S H I N G${NORMAL}\n"
    exit 1
fi

echo completed pre-push commands
